name: fempinya3_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  meta: ^1.12.0
  equatable: ^2.0.0
  table_calendar: ^3.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.0
  get_it:
  dartz:
  flutter_svg:
  customizable_counter:
  dio: ^5.8.0
  dio_http2_adapter: ^2.6.0 # Necessary for this to work on browser
  flutter_easyloading:
  logger: ^1.0.0
  go_router: ^14.2.8
  formz: ^0.8.0
  bloc_test: ^9.1.7
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.2.0
  webview_flutter_wkwebview: ^3.16.3
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  flutter_local_notifications: ^19.0.0
  shared_preferences: ^2.5.2
  mocktail: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: ^1.0.3
  flutter_lints: ^5.0.0
  test: ^1.25.8
  mockito: ^5.4.5
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/acrobatics.svg
    - assets/icons/miniRight.svg
    - assets/icons/paella.svg
    - assets/icons/question.svg
    - assets/icons/scheduleHours.svg
    - assets/icons/weightlifting.svg

