name: fempinya3_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  meta: ^1.12.0
  equatable: ^2.0.0
  table_calendar: ^3.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.0
  get_it:
  dartz:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true


